name: Link Checker

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.html'
  push:
    branches:
      - main

jobs:
  link-check:
    name: Check for Broken Links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install linkchecker
      run: sudo apt-get install -y linkchecker

    - name: Run link checker
      run: linkchecker --no-robots --no-status --check-extern --check-externally --no-follow-redirects https://dungdt5.github.io/


